-- Index the ListEvents pagination ordering (feature-events-pagination, task 1.6).
--
-- Problem
--   ListEvents now orders by:
--       ORDER BY event_date DESC NULLS LAST, id DESC
--   and no existing index can serve it. `idx_events_event_date` (000001) is
--   declared `ON events(event_date DESC)`, and Postgres defaults DESC to
--   NULLS FIRST -- so its physical order is (event_date DESC NULLS FIRST),
--   which does not match a NULLS LAST request. It also has no `id` terminator.
--   The planner therefore fell back to a full Seq Scan + top-N sort on every
--   page request.
--
-- Measured via the committed harness scripts/bench-events-ordering/bench.sql,
-- PostGIS 15-3.4, 3,268 synthetic events (the continental-scale projection from
-- feature-continental-coverage), median of 40 runs. Two independent runs:
--
--   query shape                      without      with       plan uses index?
--   page 1, no filter                2.11 / 2.15 ms -> 0.09 / 0.15 ms   yes
--   page 1, country=Nigeria          3.31 / 4.16 ms -> 0.22 / 0.36 ms   yes
--   deep page, offset 3200           3.96 / 3.72 ms -> 3.38 / 3.41 ms   NO
--
-- Roughly 15-24x on the two shapes that matter, corroborated by a second,
-- independent signal in the same EXPLAIN output: shared buffer hits for page 1
-- fall from 128 to 51. The plan changes from Seq Scan + top-N heapsort to a
-- plain Index Scan.
--
-- ⚠️ State the size of the win honestly: this saves roughly 2-4 ms per request
-- at continental scale. That is a large RATIO on a small ABSOLUTE number, and
-- the handler's unavoidable `SELECT COUNT(*)` still seq-scans regardless, so it
-- remains the dominant cost of the endpoint. This is added because it is a real,
-- twice-measured, near-free win -- not because the endpoint was slow.
--
-- ⚠️ Deep pagination is NOT helped. Past ~offset 3200 the planner correctly
-- reverts to Seq Scan + quicksort, and the index goes unread. Deep pages remain
-- an offset-pagination cost that only keyset pagination removes; that trade was
-- made deliberately in the proposal, and this index does not change it.
--
-- Locking: CREATE INDEX (not CONCURRENTLY) takes a ShareLock on `events` --
-- verified by reading pg_locks inside a transaction holding it, not assumed.
-- Reads continue; writes (i.e. ingestion upserts) block for the duration. At
-- 3,268 rows the build is milliseconds. CONCURRENTLY is deliberately NOT used:
-- golang-migrate runs each migration inside a transaction, and CREATE INDEX
-- CONCURRENTLY cannot run in one.

CREATE INDEX IF NOT EXISTS idx_events_event_date_id
    ON events (event_date DESC NULLS LAST, id DESC);
